version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Zipping application files..."
      - zip -r my-app.zip .

artifacts:
  files:
    - my-app.zip